/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadIndexRouteImport } from './routes/upload/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as ReviewerIndexRouteImport } from './routes/reviewer/index'
import { Route as PdftestIndexRouteImport } from './routes/pdftest/index'
import { Route as GooftestIndexRouteImport } from './routes/gooftest/index'
import { Route as ReviewerReviewRouteImport } from './routes/reviewer/review'
import { Route as ReviewerQueueRouteImport } from './routes/reviewer/queue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadIndexRoute = UploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewerIndexRoute = ReviewerIndexRouteImport.update({
  id: '/reviewer/',
  path: '/reviewer/',
  getParentRoute: () => rootRouteImport,
} as any)
const PdftestIndexRoute = PdftestIndexRouteImport.update({
  id: '/pdftest/',
  path: '/pdftest/',
  getParentRoute: () => rootRouteImport,
} as any)
const GooftestIndexRoute = GooftestIndexRouteImport.update({
  id: '/gooftest/',
  path: '/gooftest/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewerReviewRoute = ReviewerReviewRouteImport.update({
  id: '/reviewer/review',
  path: '/reviewer/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewerQueueRoute = ReviewerQueueRouteImport.update({
  id: '/reviewer/queue',
  path: '/reviewer/queue',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reviewer/queue': typeof ReviewerQueueRoute
  '/reviewer/review': typeof ReviewerReviewRoute
  '/gooftest': typeof GooftestIndexRoute
  '/pdftest': typeof PdftestIndexRoute
  '/reviewer': typeof ReviewerIndexRoute
  '/test': typeof TestIndexRoute
  '/upload': typeof UploadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reviewer/queue': typeof ReviewerQueueRoute
  '/reviewer/review': typeof ReviewerReviewRoute
  '/gooftest': typeof GooftestIndexRoute
  '/pdftest': typeof PdftestIndexRoute
  '/reviewer': typeof ReviewerIndexRoute
  '/test': typeof TestIndexRoute
  '/upload': typeof UploadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reviewer/queue': typeof ReviewerQueueRoute
  '/reviewer/review': typeof ReviewerReviewRoute
  '/gooftest/': typeof GooftestIndexRoute
  '/pdftest/': typeof PdftestIndexRoute
  '/reviewer/': typeof ReviewerIndexRoute
  '/test/': typeof TestIndexRoute
  '/upload/': typeof UploadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reviewer/queue'
    | '/reviewer/review'
    | '/gooftest'
    | '/pdftest'
    | '/reviewer'
    | '/test'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reviewer/queue'
    | '/reviewer/review'
    | '/gooftest'
    | '/pdftest'
    | '/reviewer'
    | '/test'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/reviewer/queue'
    | '/reviewer/review'
    | '/gooftest/'
    | '/pdftest/'
    | '/reviewer/'
    | '/test/'
    | '/upload/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReviewerQueueRoute: typeof ReviewerQueueRoute
  ReviewerReviewRoute: typeof ReviewerReviewRoute
  GooftestIndexRoute: typeof GooftestIndexRoute
  PdftestIndexRoute: typeof PdftestIndexRoute
  ReviewerIndexRoute: typeof ReviewerIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  UploadIndexRoute: typeof UploadIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/': {
      id: '/upload/'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewer/': {
      id: '/reviewer/'
      path: '/reviewer'
      fullPath: '/reviewer'
      preLoaderRoute: typeof ReviewerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdftest/': {
      id: '/pdftest/'
      path: '/pdftest'
      fullPath: '/pdftest'
      preLoaderRoute: typeof PdftestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gooftest/': {
      id: '/gooftest/'
      path: '/gooftest'
      fullPath: '/gooftest'
      preLoaderRoute: typeof GooftestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewer/review': {
      id: '/reviewer/review'
      path: '/reviewer/review'
      fullPath: '/reviewer/review'
      preLoaderRoute: typeof ReviewerReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewer/queue': {
      id: '/reviewer/queue'
      path: '/reviewer/queue'
      fullPath: '/reviewer/queue'
      preLoaderRoute: typeof ReviewerQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReviewerQueueRoute: ReviewerQueueRoute,
  ReviewerReviewRoute: ReviewerReviewRoute,
  GooftestIndexRoute: GooftestIndexRoute,
  PdftestIndexRoute: PdftestIndexRoute,
  ReviewerIndexRoute: ReviewerIndexRoute,
  TestIndexRoute: TestIndexRoute,
  UploadIndexRoute: UploadIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
